
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/shared/Footer";
import Navbar from "@/Components/shared/Navbar";
import { ToastContainer } from "react-toastify";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LiveStock Booking App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
      <Navbar></Navbar>
       <main className="bg-base-300">
         {children}
       </main>
        <Footer></Footer>
        <ToastContainer></ToastContainer>
        </body>
    </html>
  );
}
